### PR TITLE
Astra scraper

### LINKED ISSUE #9: Make astra scraper, schemas & docs
We would like to make an Astra scraper to develop a database of room and room usage data for the API.

We'll also need to develop schemas for the room data we're scraping.

- [x] Determine what we want to scrape from Astra (what data can we reliably provide via scraping?)
- [x] Create an Astra scraper (contact me if you want to work on this, I'll need to provide you the auth for it)

### PR DESCRIPTION
**Pull request by TyHil**
Resolves #9 

This Astra scraper dumps the data in JSON format with a key for each day scraped followed by a list of each room reservation in the format mentioned in issue #9 .

It stops after 90 days of fewer than 10 events. There is one persistent all day event that shows up on holidays and any semester after this one that marks "No Events Allowed". There is also a perpetual event with no time in FO 3.616, idk why. So once you get past this semester and the next you regularly have fewer than 10 events per day. I choose 90 to be safe about holidays. This works out to scraping about a year and 2 months out which takes a couple minutes on my machine.

The events are sorted by start time but this could easily be switched to room with `LocationName`.

### CODE REVIEW

**Comment by TyHil** [comment]
The current scraper logs in to Astra successfully but then throws the below error before exiting the sign in function:
`ERROR: received DOM.documentUpdated when there's no top-level frame`
@jpahm do you think you'd be able to help me out?

After that I think I'll just have to get the cookies sorted and it'll be able to make its first successful scraping request.

**Comment by jpahm** [comment]
> The current scraper logs in to Astra successfully but then throws the below error before exiting the sign in function: `ERROR: received DOM.documentUpdated when there's no top-level frame` @jpahm do you think you'd be able to help me out?
> 
> After that I think I'll just have to get the cookies sorted and it'll be able to make its first successful scraping request.

Thanks for looking into this! As far as that error goes, it pops up on the other scrapers occasionally as well -- I'm not actually 100% certain what causes it. It seems to just be an error that chromedp throws internally when it can't handle a `documentUpdated` event, though I don't think this is usually fatal. Is this error causing a panic for you or is chromedp just becoming unresponsive afterwards?

**Comment by TyHil** [comment]
Ah ok, good to know.

It was never exiting the `RefreshAstraToken` function and seemed to be hanging on ``chromedp.WaitVisible(`body`)``. Working on cookie stuff now, will lyk if I need any more help.

**Comment by democat3457** [comment]
> It was never exiting the `RefreshAstraToken` function and seemed to be hanging on `` chromedp.WaitVisible(`body`) ``. Working on cookie stuff now, will lyk if I need any more help.

@TyHil There seems to be a suggestion at this GitHub issue comment to add the `chromedp.ByQuery` argument to the WaitVisible call to explicitly specify you're querying the DOM and not just searching for text: https://github.com/chromedp/chromedp/issues/440#issuecomment-520445215

I tried it with ``chromedp.WaitVisible(`body`, chromedp.ByQuery)`` and the function no longer hung. Might be worth also adding it to the WaitVisible for the coursebook scraper.

**Review by jpahm — APPROVED** [review]
Looks good, merging now!

**Pull request merged**
